In [3]:
import copy
from keras.models import clone_model
from keras.models import load_model
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import matplotlib.pyplot as plt
import numpy as np
import progressbar
import time
import util
np.random.seed(0)

In [47]:
model_number = 3000
model = load_model('../saved_models/value_net_iter{0:06d}.h5'.format(model_number))
analyzer = util.ResultsAnalyzer(model, None, None)
end_policy = analyzer.extractPolicy()
analyzer.processPolicy(end_policy)

[[2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 2. 2. 0. 0. 0. 2. 2. 2.]
 [1. 1. 2. 2. 2. 0. 2. 0. 0.]
 [2. 1. 1. 1. 2. 2. 1. 1. 1.]
 [2. 1. 1. 1. 1. 2. 2. 1. 1.]
 [2. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 1. 1. 1. 1. 1. 1. 1. 1.]]
0 & \wt & \wt & \wt & \wt & \wt & \wt & \wt & \wt & \wt \\ 
1 & \ob & \wt & \wt & \ag & \ag & \ag & \wt & \wt & \wt \\ 
2 & \ob & \ob & \wt & \wt & \wt & \ag & \wt & \ag & \ag \\ 
3 & \wt & \ob & \ob & \ob & \wt & \wt & \ob & \ob & \ob \\ 
4 & \wt & \ob & \ob & \ob & \ob & \wt & \wt & \ob & \ob \\ 
5 & \wt & \ob & \ob & \ob & \ob & \ob & \ob & \ob & \ob \\ 
6 & \wt & \ob & \ob & \ob & \ob & \ob & \ob & \ob & \ob \\ 
7 & \wt & \ob & \ob & \ob & \ob & \ob & \ob & \ob & \ob \\ 
8 & \wt & \ob & \ob & \ob & \ob & \ob & \ob & \ob & \ob \\ 

